YosysHQ/arachne-pnr

- src/global.cc
- src/netlist.cc
- src/netlist.hh
- src/pack.cc
- src/place.cc
- src/route.cc
Hi.  I added the missing stuff to be able to generate bitstreams using the SB_WARMBOOT module.
The slighly weird code in `place.cc` is due to the fact that the WARMBOOT cell does not have a valid tile (it is 0 0), so it's not possible to call `valid()` on the tile, or to lookup the nonrouting cbits for the the tile type.
Tested on iCEstick iCE40HX1K.
> Finish implementation of WARMBOOT cells

- Makefile
Need this to build arachne-pnr with icebox installed to an alternate location.
> Parametrize chipdb-Xk.txt location in Makefile

- src/arachne-pnr.cc
- src/chipdb.cc
Windows will convert `\n` to `\r\n` and vice versa on read/write in text mode, binary mode must be stated explicitly to prevent this. This fixes #28
> Fix chipdb read failure on Windows

- src/bstream.hh
On 64-bit systems the 'size_t' type is translated to 'unsigned long long', therefore there is need for additional overload of '>>' nad '<<' operators.
This change was tested on mingw-w64-gcc-6.1.0 toolchain and works as expected.
> Support for 64-bit size_t offsets in bstream.hh

- Makefile
This is a consequence of my old patch. Sorry for the inconvenience.
The merge got "VER" when the rest of the Makefile uses "ARCHNE_VER" to make it more arachne specific.
> Fixed VER -> ARCHNE_VER in Makefile

- src/global.cc
This helps detecting problems related to issue #81
> Notify user if not able to use specific pin for global buffer output

- src/blif.cc
- src/pcf.cc
* added more helpful messages to BlifParser's fatal errors
* made PCF parser tolerate Lattice-style -pullup options
* fixed incorrect word index in PCF parser: was 1, should be i
> Minor enhancements to BLIF and PCF parsers

- src/pcf.cc
- src/pcf.hh
- src/util.cc
- src/util.hh
This allows users to dis/enable pull-ups using constraints using the -pullup option.
This option is supported by the SBT tool-chain.
This patch should also fix some bugs in the set_io options parser (take a look at the [1] vs [i] changes)
It also adds a function called void note(const std::string &msg) used to report information. The code uses it to inform the user that a pull-up constraint was applied.
> Added -pullup support to set_io constraint

- src/io.cc
Currently the code assumes that $_TBUF_ output (Y) is connected to just one point: a top-level port.
The problem is that when we use inout pins Y is connected to the top-level port AND internal logic using the top-level port as input.
In this case the number of connections for the net that connects the $_TBUF_ to the outside world is more than 2 and connection_other_port returns NULL. In this case arachne aborts saying the $_TBUF_ must be connected to an output or inout port.
This patch allows more than 2 connections and selects the proper connection to use.
I verified it in a design with 17 $_TBUF_ used in 2 different ways.
The patch passed the regression tests.
It look bigger than what it really is because I added some comments about what the code is doing.
> Fixed $_TBUF_ cases where the outputs are internally used

- .gitignore
- Makefile
- src/arachne-pnr.cc
- src/util.cc
This depends on my previous #73 PR.
The last commit modifies arachne-pnr to mount emscripten's NODEFS on `/x` if the resulting javascript is run under nodejs. This is useful for testing so that the resulting javascript can interact with files on the host filesystem. By default, emscripten-compiled output can only access its in-memory virtual filesystem. It also isn't possible to mount additional emscripten filesystems over the root, so as a compromise NODEFS is mounted on `/x`. After this change, it is possible to run commands like
```
$ nodejs ./bin/arachne-pnr.js -d 8k /x/tests/simple/carry.blif -o /x/carry.asc
```
This will create a `carry.asc` in the current working directory.
> Better emscripten support

- src/global.cc
- src/netlist.cc
- src/netlist.hh
- src/place.cc
This contains a few small UltraPlus changes:
- Set the SPI enable bits correctly
- Support trimming of the HFOSC (an undocumented feature), using the SB_HFOSC_TRIM primitive
- Fix a bug where the oscillator output could collide with another global buffer (thanks to Nikolaj for finding and reporting this one)
> Minor UltraPlus Improvements

- src/netlist.cc
- src/route.cc
Some of Lattice's example code ties ACCUMCI and SIGNEXTIN of the SB_MAC16s to 0, instead of leaving them unconnected. Functionally this is equivalent, but arachne-pnr doesn't have find pins in the chipdb, because they're for cascading, so was failing. This PR ignores them when they're at constant 0, which is the correct behaviour.
In the future a proper implementation of DSP cascading will need to be done, placing DSPs in a chain similar to LUT carry connections based on the connections of these pins.
> Ignore ACCUMCI and SIGNEXTIN when tied to 0

- src/bstream.hh
- src/chipdb.cc
- src/chipdb.hh
- src/pack.cc
- src/pcf.cc
- src/place.cc
Some packages of the 1k and 8k have fewer PLLs than others, due to the VccPLL/GNDPLL not being bonded out. icestorm signifies this in the chipdb using the `LOCKED` entry followed by a list of packages where the cell isn't available, but until now arachne-pnr was ignoring this.
NB: because of modifications to the chipdb parsing, binary chipdbs will need to be rebuilt after this PR is merged (this should be automatic if using the normal Makefile).
> Fix handling of LOCKED attribute on extra cells, if not available in a certain package

- src/chipdb.cc
If they don't, e.g. because of "make install" issues, it would previously cause an obscure and hard-to-debug error message.
https://twitter.com/fpga_dave/status/962319776306663424
> Ensure chipdb and arachne-pnr versions match

- src/chipdb.cc
- src/configuration.cc
- src/constant.cc
- src/io.cc
- src/line_parser.cc
- src/netlist.cc
This prevents missing dependencies in the header files.
> Include associated headers first

- Makefile
- src/arachne-pnr.cc
- src/util.cc
Per [##openfpga discussion](https://irclog.whitequark.org/~h~openfpga/2018-02-19#1519051451-1519048841;), builds on Windows using msys2 should be using the Unix directory structure to avoid `chip-db` mismatches in case the user forgets to copy them to the invocation directory of the binary (relevant for both general usage and tests).
These changes to where `arachne-pnr` looks for `chip-db`s works fine w/ msys2; I do not have the ability to test with MXE, but the compiler command line looks correct in the `Makefile`.
> Allow Unix directory structure for arachne paths on Windows for msys2.

- src/pcf.cc
Most designers are not familiar with the low level structure of a particular FPGA, and a tile doesn't mean a whole lot of them.
With this patch, instead of this:
```fatal error: pcf error: multiple OUTPUT_CLK drivers in PIO at (0, 6)```
Arachne will now report this:
```fatal error: pcf error: multiple OUTPUT_CLK drivers in PIO (RAMUB,RAMOE) at (0, 6)```
> Print PIO package pin names when inconsistencies are detected.

- src/pcf.cc
This patch checks if an LVDS input pin has been assigned to a DPxxA input, and aborts when it's a DPxxB input.
Without this patch, arachne asserts during the placement phase.
I don't know what the official Lattice tools do in such case. It's possible that it can deal with assignments to both inputs? In that case, for compatibility, it would be better for arachne to behave the same. But that'd be a much more complex fix.
This fixes issue #50 and issue #37.
> Check SB_LVDS_INPUT against DPxxB

- src/arachne-pnr.cc
Instead of the previous `/x`, there is now `/hostcwd` for the current
directory and `/hostfs` for the root directory. (Due to limitations in
emscripten, it is not possible to simply make the real root filesystem
appear at / in the emscripten filesystem.)
> emscripten: Improve mount points for accessing "real" files

- Makefile
Use relative path for `bin/arachne-pnr-host` in Makefile. This fixes the execution of  `bin/arachne-pnr-host` when the source is cross-compiled for Windows using mingw32 and wine.
cc @cseed @cliffordwolf
> Fix Makefile for mingw32 and wine

- src/pcf.cc
Previously arachne-pnr was only considering internal oscillators as occupying one global network each, without considering the different types of globals and what they can drive, when promoting globals. By moving oscillator placement to the constraints placement phase, these become known during global promotion and fix occasional conflicts, such as was occurring in tinyfpga/TinyFPGA-Bootloader#5
> Fix HFOSC/LFOSC and globals conflict

- src/arachne-pnr.cc
- src/netlist.cc
- src/netlist.hh
The 'boundary_nets' method uses 'connection_other_port' to check if a net is connected to a physical pin:
https://github.com/cseed/arachne-pnr/blob/5d830dd94ad956d17d77168fe7718f22f8b55b33/src/netlist.cc#L480
However, this method assumes that there are a maximum of 2 ports connected to the net.
When a netlist is given that violates this assumption, the net is not listed as a boundary net which will result in internal check failures later on.
This commit adds a 'check_boundary_nets' method that ensures that boundary nets meet the expectations. If they do not, it fails gracefully.
This commit fixes both issue #77 and #100.
Tom
> Check that boundary nets are connected to a physical pin and nothing else.
